#!/usr/bin/env python3
from pathlib import Path
import csv
import json
import sys
from common import ROOT

required=[
    "README.md","README-APLICACAO.md","config/security-baseline.json","config/security-registry.json",
    "controls/CONTROL-MATRIX.csv","policies/access-control.md","policies/secure-sdlc.md",
    "runbooks/security-incident.md","evidence/source/SOURCE-INVENTORY.json",
]
errors=[]
for rel in required:
    if not (ROOT/rel).is_file(): errors.append(f"missing:{rel}")
for path in ROOT.rglob("*"):
    if not path.is_file(): continue
    rel=path.relative_to(ROOT).as_posix()
    if any(part in {".git","release"} for part in path.parts): continue
    if path.name==".DS_Store" or "__MACOSX" in path.parts or "__pycache__" in path.parts or path.suffix==".pyc": errors.append(f"system-file:{rel}")
    if path.suffix.lower() in {".zip",".tar",".gz",".tgz"}: errors.append(f"nested-archive:{rel}")
    if path.stat().st_size==0: errors.append(f"empty-file:{rel}")

baseline=json.loads((ROOT/"config/security-baseline.json").read_text())
if baseline.get("status")!="PENDING_INSTITUTIONAL_APPROVAL": errors.append("baseline-status-invalid")
if baseline.get("fail_closed") is not True: errors.append("fail-closed-disabled")
registry=json.loads((ROOT/"config/security-registry.json").read_text())
for module in registry.get("modules",[]):
    if module.get("state")=="BLOCKED_EXTERNAL_EVIDENCE" and not module.get("evidence_required"):
        errors.append(f"external-evidence-not-required:{module.get('name')}")
with (ROOT/"controls/CONTROL-MATRIX.csv").open(encoding="utf-8") as handle:
    rows=list(csv.DictReader(handle))
if len(rows)!=25: errors.append(f"control-count:{len(rows)}")
for row in rows:
    if not row["owner"].strip() or not row["evidence"].strip(): errors.append(f"control-incomplete:{row['control_id']}")

forbidden=("Generated by","As an AI","Enterprise System","MVP","TODO implement","placeholder implementation","regenera-agent","agent CLI")
for path in ROOT.rglob("*"):
    if not path.is_file() or any(part in {"release",".git"} for part in path.parts): continue
    if path.name=="validate.py": continue
    try: text=path.read_text(encoding="utf-8")
    except UnicodeDecodeError: continue
    for token in forbidden:
        if token.lower() in text.lower(): errors.append(f"forbidden-content:{path.relative_to(ROOT)}:{token}")

if errors:
    print("VALIDATION: FAIL"); print("\n".join(errors)); sys.exit(1)
print(f"VALIDATION: PASS ({sum(1 for p in ROOT.rglob('*') if p.is_file())} files)")
