/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Regenera Bank v4 API (from Guia)
 * OpenAPI spec version: 4.0.0
 */

export type PostAuthFaceEnrollment200 = {
  livenessApproved?: boolean;
  success?: boolean;
};
