from common import *
import re, json
PATTERNS={
 'private_key':re.compile(r'-----BEGIN (?:RSA |EC |OPENSSH )?PRIVATE KEY-----'),
 'aws_key':re.compile(r'AKIA[0-9A-Z]{16}'),
 'github_token':re.compile(r'gh[pousr]_[A-Za-z0-9_]{20,}'),
 'generic_secret':re.compile(r'(?i)(?:password|secret|token)\s*[:=]\s*["\']?[A-Za-z0-9+/=_-]{16,}'),
 'unsafe_claim':re.compile(r'(?i)\b(?:100% compliant|approved for production|gold master|homologado pelo bacen)\b'),
 'agent_trace':re.compile(r'(?i)\b(?:as an ai|generated by|claude|gemini|copilot|chatgpt)\b'),
}
EXACT_EXCLUSIONS={'tools/security_scan.py':'implementação das assinaturas do scanner','tests/test_security.py':'fixtures isolados de detecção'}

def main():
    findings=[]
    for p in sorted(ROOT.rglob('*')):
        if not p.is_file(): continue
        rel=str(p.relative_to(ROOT))
        if rel.startswith(('evidence/','generated/')) or '__pycache__' in rel or p.suffix=='.pyc': continue
        if rel in EXACT_EXCLUSIONS: continue
        if p.stat().st_size>2_000_000: findings.append({'file':rel,'rule':'oversized_file'}); continue
        try: text=p.read_text(encoding='utf-8')
        except UnicodeDecodeError: findings.append({'file':rel,'rule':'binary_file'}); continue
        for name,rx in PATTERNS.items():
            if rx.search(text): findings.append({'file':rel,'rule':name})
    report={'status':'PASS' if not findings else 'FAIL','findings':findings,'exact_exclusions':EXACT_EXCLUSIONS}
    json_dump(EVIDENCE/'SECURITY-REPORT.json',report)
    print(json.dumps(report,ensure_ascii=False))
    return 0 if not findings else 1
if __name__=='__main__': raise SystemExit(main())
