apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: regenera-channel-android
  description: Componente Regenera do domínio android.
  annotations:
    regenera.io/criticality: high
spec:
  type: service
  lifecycle: experimental
  owner: team-android
  system: regenera-bank
